# Etapa 1: Build de la app
FROM node:20-alpine AS builder
WORKDIR /app

# Copia dependencias y fuentes
COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

# Etapa 2: Servidor NGINX
FROM nginx:alpine
# Copiar el build al directorio público de nginx
COPY --from=builder /app/build /usr/share/nginx/html

# (opcional) Copiar configuración personalizada
# COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
